const createAnimalTable = `CREATE TABLE animals (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);`

const createTypesTable = `CREATE TABLE types (
  type_id SERIAL PRIMARY KEY,
  animal_id INT NOT NULL REFERENCES animals (id) ON DELETE CASCADE,
  type_name VARCHAR(255) NOT NULL,
  type_image VARCHAR(1000)
);`

const createBreedsTable = `CREATE TABLE breeds (
breed_id SERIAL PRIMARY KEY,
animal_id INT NOT NULL REFERENCES animals (id) ON DELETE CASCADE,
type_id INT NOT NULL REFERENCES types (type_id) ON DELETE CASCADE,
breed_image VARCHAR(1000),
breed_name VARCHAR(255) NOT NULL,
price INT,
details VARCHAR(10000)
);`

const createReviewTable = `CREATE TABLE reviews (
  review_id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  message VARCHAR(1000)
)`

const insertBreeds = `INSERT INTO breeds(animal_id, type_id, breed_image, breed_name, price, details)
VALUES(873949768395882498, 874505992323825665, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/bsfpupae.jpeg', 'Live Black Soldier Fly Pupae (price per 1000)', 40, 'BSF pupae differ from pre-pupae in that they have already formed hard shells and will appear inactive. Pupae must be placed in an environment at 81 °F for proper development.')
`
// VALUES(873949768395882498, 874505992323825665, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/driedbsf.jpeg', 'Dried Black Soldier Fly Larvae (price per 5 lbs)', 30 ,'Freshness is the best- Our black soldier fly larvae are fresh dried, when you open the bag, you can feel the quality. It is perfect feeds for poultry like chickens, ducks and wild birds like blue birds, make them happy and eggs stronger. High in Calcium- BSFL has more Calcium, around 80-85X mealworms, protein around 40%.It will help eggshells stronger and baby chicken/birds better growing up.'),
// (873949768395882498, 874505992323825665, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/liveBSF.jpg', 'Live Black Soldier Fly Larvae (price per 100)', 8 , 'Premium quality - Our Black Soldier Fly Larvae are raised on a nutrient-rich diet and carefully selected for their size and health. Complete nutrition - Our Black Soldier Fly Larvae are packed with protein, vitamins, and minerals to keep your pets healthy and happy.')

//MEALWORMS DONE:
// VALUES(873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/mealworms.jpeg', 'Live Mealworms (price per 100)', 15, 'Live Mealworms are between 1/2 to 1 in long and apx 4-5 mm diameter. If temperatures above 85 degrees must purchase a cold pack. If your temperatures below 40 at night must purchase a heat pack. If below 35 must be held at post office.'),
// (873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/bagWorms.jpeg', 'Dried Mealworms (price per 5 lbs)', 49, 'Our mealworms make a great treat for most poultry including chickens, ducks, and turkeys but the high protein found in our dried mealworms makes it a great protein supplement too. When your hens are going through a molt -mealworms will provide an excellent protein boost that can benefit feather growth. Mealworms make it easy to work with your hens because with a bag of mealworms in your hand they will follow you anywhere.'),
// (873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/darkling.jpeg', 'Live Darkling (Mealworm) Beetles (price per 55)', 11, 'They are fed fresh veggies, apples and bran. Their bedding is cleaned weekly. All of our Darkling Beetles are raised in a heated sterilized environment giving you some of the best and healthiest beetles on the market.'),
// (873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/driedDarkling.jpg', 'Dried Darkling (Mealworm) Beetles (price per 11 lbs)', 60,'Dried Darkling Beetles 100% natural Non GMO The Mealworm is a species of darkling beetles. Our dried Darkling Beetles are an excellent protein source for bluebirds- chickadees- robins and other wild birds. They also make an excellent treat for chickens, turkey,ducks, pheasants, reptiles. Can last up to one year or two when kept in a cool dry place.'),
// (873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/superworms.jpeg', 'Live Superworms (price per 250)', 40, 'Large - between 1.5 to 2 in long and apx 1/4 in diameter. If temperatures above 85 degrees must purchase a cold pack. If your temperatures below 40 at night must purchase a heat pack. If below 35 must be held at post office.'),
// (873949768395882498, 874505992323858433, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/waxworms.jpg', 'Live Waxworms (price per 250)', 30, 'Live waxworms are apx 1 in long and apx 8 mm in diameter. If temperatures above 85 degrees must purchase a cold pack. If your temperatures below 40 at night must purchase a heat pack. If below 35 must be held at post office.')
//TURTLES DONE:
// VALUES (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/boxTurtle.jpeg', 'Eastern Box Turtles', 175 , 'This species gets its name from the ability to hinge its shell closed on both ends. They are opportunistic omnivores that will eat both plant and animal matter, such as waxworms, earthworms, snails, berries, fruits, and grasses. They make wonderful pets that can learn their keepers voice and develop individual personalities. Babies tend to be more carnivorous, consuming mealworms and waxworms very readily. However, adults tend to be more omnivorous, meaning they eat both plant and animal material. This includes leafy greens, grapes, carrot, and various insects and worms. Babies and adults are both active animals, and feed readily throughout the day. They avoid high heat and dry conditions. They learn their keepers voice and appearance as well, helping form a bond, usually through food offerings.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/slider.jpeg', 'Red Eared Slider Turtles', 19 , 'These are some of the most popular pet turtles on the planet due to their beautiful coloration and personable demeanor. Red eared sliders can live for over 25 years with good care. '),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/sulcata.jpeg', 'Sulcata Tortoises', 130 , 'Baby sulcatas are nothing short of adorable, with shell lengths of 1.5 to 2 inches. These tortoises have wonderful personalities and thrive in captivity. The third largest tortoise in the world, this African reptile attains a large size and is an extremely popular pet reptile. They are also herbivorous, meaning they eat plants, fruits, and vegetables. Babies will chase and eat the occasional insect. Focus on offering them high fiber (and low protein) diets. Native to the Sahara desert, these tortoises prefer drier habitats, and should not be kept in humid environments. They are docile pets that never fail to impress onlookers. In fact, whenever someone sees one of our adults, they immediately want to know how they can buy one.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/russian.jpeg', 'Russian Tortoises', 150 , 'This social animal remains fairly small, reaching lengths of just 6" to 8”. This species is, in our experience, the single toughest tortoise in the world. They generally do extremely well in captivity, have very long lifespans, and are undemanding pets. They can be kept outdoors year round as long as temperatures do not dip much below 25F and insulated hide spots are provided. They are heavy-built and round in shape, however, they are surprisingly agile and enjoy climbing and exploring. They have long claws that help with climbing and are known to be avid diggers too. They are known for burying themselves to avoid extreme hot and cold temperatures.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/cherryhead.jpeg', 'Cherryhead Tortoises', 225 , 'Black shell color, usually with yellow highlights in the centers of each scute of their shell, which are present from hatching (the black color grows in with age). This type of redfoot tortoise is more contrasted than the standard redfoot tortoises. The skin is black, with bright red spots on the front and rear legs. Head color is generally black skin with blood red markings (instead of the normal orange or yellow scales present on standard redfoots). We consider them "watermelon" shaped; somewhat elongated and rounded, no matter which angle you are looking at them from. This tortoise is naturally a browser, and will wander about munching on broadleaf plants and fallen fruit the majority of its natural life. They are known to eat meat in the wild, seen eating dead animals, worms and snails. In captivity, redfoot tortoises will eat almost anything well, such as leafy weeds and clover (dandelions are a favorite), fruit, vegetables and they love Mazuri tortoise diet.Adult cherryhead tortoises are interactive and curious tortoises. They are usually unaggressive towards eachother and can usually be kept long term in mixed-sex groups. They are not damaging to their environment, rarely digging holes or burrows. Most redfoots will eagerly come to their keepers looking for food once they are comfortable in their environments.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/pancake.jpeg', 'Pancake Tortoises', 600 , 'True to their name, pancake tortoises are a very flat tortoise, designed to fit into the narrow crevices that they live in naturally. With a small adult size, these pretty tortoises have radiating patterns on their shells, much like star tortoises. Their shells are very soft for a tortoise, and quite flexible when held. While this helps them fit into narrow cracks in the rock, it leaves them vulnerable to predators that would have problems trying to eat harder-shelled tortoises. This tortoise is naturally a grazer, and will come out for short amounts of time to eat, dashing back and fourth to the safety of the rocks. In captivity, pancake tortoises will graze on low plant leaves as broadleaf weeds and clover (dandelions are a favorite). Vegetables can be added to the diet for variety, but fruit should generally be avoided. In an indoor enclosure, they do well on a staple diet of spring mix. Adult pancakes tortoises are secretive, fast moving tortoises. They are considered the fastest tortoise on the ground, which is probably to help them get out of harms way. They are un-aggressive towards eachother in most cases, and do little damage to their environment (little or no digging or burrowing). Because of their natural shelters, they have developed soft shells that make them quick to hide if they feel threatened. They spend a huge majority of their day hidden in tight quarters, and this should not be changed in captivity. Many keepers put them in wide open cages so that they can see them, but this stresses the tortoises as they constantly feel in danger. With a natural home in steep, rocky terrain and with a low center of gravity, they are extremely good climbers. They are well known among tortoise keepers as escape artists because of their ability to climb as well as a low profile, making it easy for them to get through gaps as small as 1" in size. We have had them escape from enclosures that seem mathematically impossible to escape from. For this reason, it is best to keep them in a way that if they do escape their enclosure, there is another barrier to stop them after that. Example of a proper way to house them is below.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/razorback.jpeg', 'Razorback Musk Turtles', 160 , 'Razorbacks are much lighter in color than most muds and musks. From gray to almost silver, or light brown to orange with spotted or streaked darker markings, they are one of the prettiest. As their name suggests, they have a very prominent keeled shell, and a hinged bottom. Razorbacks are omnivores, taking pellets, fish, crustaceans, insects, meat, worms and aquatic plants. Shallow bottom dwellers, Razorbacks bask more than do most muds and musks. They are easily kept with other muds and musks, and or in a community tank with other turtle species. As adults they keep much of their juvenile color, and do well in lager set ups ,or as shallow outdoor pondgarbage disposals.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/snakeNeck.jpeg', 'Siebenrock Snake Neck Turtles', 260 , 'Siebenrocks snake-necked turtle (Chelodina siebenrocki), is a very odd looking turtle from the swamps, marshes and lagoons of the southern coast of New Guinea west of the Fly River, and is also thought to occur at Cape York in Australia. With a head and neck equal to its shell length, this carnivorous turtle is a super predator - with powerful neck muscles it launches its head with amazing speed, seizing its prey. Despite Siebenrockis impressive hunting skills, it is not aggressive, and does not bite when handled. Siebenrocks Snake-necked Turtles are one of the most impressive tank turtles to keep. They are outstanding swimmers and put on a fine display when stalking fish and insects. Our hatchlings readily take pellets, cut or small live fish, cut beef heart, super and earth worms. Chelodina Siebenrocki can fold its long neck and tuck it completely under its shell - yet it often forages about with its neck fully extended, ready to retract as fast as it can strike. This intriguing turtle does not need to bask, and will endlessly fascinate keepers - who cannot help but do a double take at one of natures true oddities.'),
// (873949768395849730, 874505992323792897, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/leopard.jpeg', 'Leopard Tortoises', 300 , 'This tortoise is naturally a grazer, and will wander about nibbling on grass the majority of its natural life. In captivity, leopard tortoises will graze on grasses, as well as leafy weeds and clover (dandelions are a favorite). As babies, we focus more on feeding them a wide mix of leafy greens (spring mix), since they have a harder time eating the more tough grass. Vegetables can be added to the diet for variety, but fruit should generally be avoided. Adult leopard tortoises are peaceful, slow moving tortoises. They are un-aggressive towards eachother in most cases, and do little damage to their environment (little or no digging or burrowing). Some individuals can be skittish if spooked, but most will eagerly come to their keepers looking for food once they are comfortable in their environments. They are not very good climbers and make little attempt to escape, so a short, basic wall will contain most leopard tortoises. Hot, dry climates. This is one of the few tortoises that really struggles in high humidity areas (they can handle moderate humidity). They do not hibernate, but will go through a winter slow down period during cooler weather and shortened daylengths.')






//FROGS DONE:
// VALUES (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/pacman.jpeg', 'Pacman Frogs', 30, 'This very impressive Argentine horned frog attains a snout-to-vent size of up to seven inches, making them one of the largest frogs in the world. Their appetites are nothing short of legendary, with adults capable of consuming a rat. Pacman frogs are affectionately named after the 1980s video game character Pac-man, because they appear to be all mouth, and gobble up everything in front of them! These voracious beasts are ambush predators, which means they sit-and-wait for unsuspecting prey to wander across their path. This is why they do not need much space to exist—they are not very active. But, feeding time could be described as lightning fast and aggressive.' ),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/bullfrog.jpeg', 'Bullfrogs', 28, 'These tremendous frogs are incredible predators, willing to eat anything they can swallow, including insects, rodents, birds, and even baby turtles. They attain a snout to vent length of 6" to 8", can weight up to nearly two pounds, and have an unmistakable croak. Bullfrogs have an olive green back and sides blotched with brown markings along with a whitish belly spotted with yellow or grey. These frogs are completely aquatic, which allows for students to create fun underwater habitats! '),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/leopardFrog.jpeg', 'Leopard Frogs', 30, 'These prolific amphibians make excellent captive frogs, and do well in enclosures or ponds. Their big appetites make for considerable entertainment at feeding time, and they can reach snout to vent lengths of just over four inches.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/bumblebee.jpeg', 'Bumblebee Poison Dart Frogs', 50, 'Like all Dendrobatidae, D. leucomelas secrete toxins from their skin which they gain from eating certain unspecified arthropod prey items. It is uncertain precisely which arthropods lend their toxicity to which genus of Dendrobatidae, but one such arthropod is thought to have been identified as a possible source of the toxin for Dendrobatidae P. terriblis, and it is a local variant of the Melyrid beetle. Dendrobatidae toxins vary from species to species, but some are extremely potent neurotoxins. The alkaloid toxins, secreted from the frogs skin, interfere with nerve impulses, which can lead to heart failure or fibrillation. D. leucomelas, despite being known as a poison dart frog, was not used for the purpose of poisoning hunting darts. In reality, only members of the Phyllobates genus were used for such a purpose, although, like them, leucomelas possess extremely potent toxins. They are thought to be the most toxic species of their genus, and their poison could potentially kill an animal as large as a human. The initial symptoms are a searing, burning pain, fever, and elevated pulse, which are soon followed by convulsions and finally paralysis.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/Cane.jpeg', 'Cane Toads', 15, 'This amphibian species attains a huge size, with the record being almost six pounds and 15" from snout to vent. Absolute eating machines, and avid breeders in captivity. Truly an impressive animal. The cane toad (Rhinella marina), also known as the giant neotropical toad or marine toad, is a large, terrestrial true toad native to South and mainland Central America, but which has been introduced to various islands throughout Oceania and the Caribbean, as well as Northern Australia. It is a member of the genus Rhinella, which includes many true toad species found throughout Central and South America, but it was formerly assigned to the genus Bufo.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/egyptian.jpeg', 'Egyptian Toads', 10, 'This species is also called the European Green toad. Your square marked toads terrarium should be inspected and spot cleaned daily when changing the water. Every two to three weeks clean out the tank completely and sterilise using a reptile/amphibian friendly disinfectant.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/fireBelly.jpeg', 'Fire Bellied Toads', 4, 'These are some of the most popular amphibians in the world, due to their beautiful coloration, small size, and high activity level. Their appetites are almost insatiable, making them very entertaining pets. They are also easy to breed in captivity. They are noted for their bright green and black coloration on their backs, and brilliant orange and black on their underside. In the wild, B. orientalis eat various types of small aquatic arthropods (among other things) from which they obtain Carotene, which helps to color their bellies. These bright colors serve as a warning to predators of toxicity. The toxin is secreted through the skin mostly on the hind legs and sometimes the belly in a milky-like substance when the frog is disturbed or frightened. Not only will they emit this toxin, they will also lay on their back to show the colour of the belly, indicating its toxicity to any predators.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/amazonMilk.jpeg', 'Amazon Milk Frogs', 80, 'The milk in the name comes from the milky colored fluid these frogs excrete when stressed. Amazon Milk Frogs inhabit humid rainforest regions. They often inhabit vegetation which extends over permanent, slow moving water sources. Like most other species of frog, Amazon milk frogs are insectivorous. They will consume almost any type of small arthropod they can overpower and swallow. Trachycephalus resinifictrix is commonly found in captivity. They are a species of moderate difficulty to care for, requiring a significant amount of space, humidity (this can be achieved via a water area and misting once or twice daily) and regular cage maintenance to ensure a clean healthy environment.'),
// (873949768395849730,874505992323760129, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/redEyed.jpeg', 'Red Eyed Tree Frogs', 50, 'Red-eyed Tree Frogs (Agalychnis callidryas), as their name implies, have red eyes with vertically narrowed noses, a vibrant green body with yellow and blue striped sides and bright orange feet. There is a great deal of regional variation in flank and thigh coloration. Young frogs are typically brown in color and turn greener as they mature, although adult frogs can change their color slightly depending on mood and environment. Red-eyed tree frogs have soft, fragile skin on their stomach, and the skin on their back is thicker and rougher. The red-eyed tree frog has three eyelids and sticky pads on its toes. Phyllomedusid tree frogs are arboreal animals, meaning they spend a majority of their life in trees, which also makes them great jumpers. Red-eyed tree frogs are not poisonous and rely on camouflage to protect themselves. During the day, they remain motionless, cover their blue sides with their back legs, tuck their bright feet under their stomach, and shut their red eyes. Thus, they appear almost completely green, and well hidden among the foliage.')
//LIZARDS DONE:
// VALUES (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/beardieCard.jpg', 'Bearded Dragon', 120, 'Also known as beardies, the bearded dragon is native to Australia. This lizard is a pro at adapting to extreme temperatures and moisture shifts, making it an easy beginner reptile for herp enthusiasts. Bearded dragons tend to be calm and friendly. Beardies are omnivores that like to gobble up both plant and animal foods, including insects, mealworms, collard greens and dandelion greens.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/chameleon.jpg', 'Chameleon', 60, 'This type of lizard comes in over 200 types, including the popular veiled chameleon, Jacksons chameleon and pygmy chameleon. The most friendly of the bunch is the veiled chameleon, which originates in Saudi Arabia and Yemen. Chameleons do not tolerate much handling and are best admired through the glass of their habitat. An occasional short stroll over your fingers then back onto a branch in their home is more than enough stimulation. The veiled chameleon is insectivorous and dines on crickets, mealworms, superworms, waxworms and roaches supplemented with calcium and vitamins.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/crestedGeckoCard.jpeg', 'Crested Gecko', 80, 'The cute crested gecko comes to us from the island of New Caledonia. They enjoy some handling, especially the freedom to roam around on your hand or arm. They are docile and easy to manage. This type of gecko would make a good family pet for a household with older children. Crested geckos are omnivorous and do well with a commercial gecko diet, feeder insects (such as crickets and Reptile Munchies Mealworms) and an occasional treat of freshly diced tropical fruits.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/anoleCard.jpeg', 'Green Anole', 15, 'You will find brown and green anoles scurrying around the southern parts of the United States, including Georgia and South Carolina. While these lizards are not aggressive, they are fast, making them fun to watch but hard to hold or pet. Because they are so speedy, they are best suited for a patient, attentive teenager or adult. Anoles enjoy eating insects and spiders, including small crickets.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/iguanaCard.jpeg', 'Iguana', 50, 'While many lizards manage to stay hand-size or smaller, iguanas can grow to three to six feet long and weigh up to 20 pounds. They are native to Central America and South America. They make great pets for adults who will be mindful of their large claws. They are generally a calm pet, but they may bite (which can be painful) if provoked. Iguanas are herbivores that prefer to munch on leaves, flowers and fruits such as dark leafy greens, dandelions, clover, marigolds, apple blossoms, bell peppers and cucumbers. You can also offer them pelleted iguana food.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/leopardGeckoCard.jpeg', 'Leopard Gecko', 30, 'This pet lizard originates in the Middle Eastern countries of Iraq, Iran, Afghanistan and India. They are known as very hardy and calm pets, making them a top seller at pet stores. In the wild, you will find leopard geckos catching insects for their meals. As pets, they thrive well on crickets, mealworms, waxworms, superworms and roaches boosted with nutrient-rich Gut Load Cricket Drink.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/skinkCard.jpeg', 'Skink', 175, 'You will find the blue-tongue skink naturally roaming the woodlands and fields of Australia, New Guinea and Indonesia. As juveniles, skinks appear nervous and cautious around humans. They will mature into docile adult pets with consistently gentle interactions, like allowing them to walk on your hands. The blue-tongue skink is an omnivore. In captivity, they enjoy a mix of chopped carrots, mustard greens, dandelion greens, crickets, mealworms and waxworms.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/teguCard.jpeg', 'Tegu', 85, 'These South and Central American lizards are common in Brazil, Paraguay and northern Argentina. The Argentine black and white tegu, red tegus and gold tegus may also be found roaming Florida properties. Tegus tend to be docile but grow up to four feet long, making them best suited for experienced reptile handlers. These lizards are omnivores, eating a variety of fruits, eggs from ground nesting birds, small reptiles and rodents.'),
//  (873949768395849730, 874505992323727361, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/monitorCard.jpeg', 'Monitor', 70, 'About 80 species of monitor lizards live in the grasslands, savannahs and rocky terrain of Africa, Asia and Oceania. The savannah monitor is a good pet option for an adult who can spend lots of time and have a lot of patience with the reptile. When handled gently as a juvenile, an adult monitor will generally be docile and calm. Some species of monitors are carnivores. Savannah monitors kept as pets do well on an insect diet of crickets, mealworms, waxworms and roaches.')
//GEESE DONE:
//VALUES (873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/toulouseCard.jpeg', 'Toulouse Geese', 25, 'Developed in the 1850s the Toulouse was bred for exhibition purposes. This very calm breed is slower growing, not reaching full maturity until at least three years old. Their plumage comes in shades of grey.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/africanCard.jpeg', 'African Geese', 18, 'A curious goose, the African was introduced to the U.S. in the mid 1800s. It has a black knob on the tops of its head and a dark stripe down the back of its neck. It is a smaller bird than the Embden and Toulouse. Its adult weight is 18-22 pounds. Egg-laying season is typically March through May but may fluctuate according to the Spring weather.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/sebatopolCard.jpeg', 'Sebastopol Geese', 99, 'Sebastopol geese have a very unique appearance. They have been around for hundreds of years, and are thought to have originated from the countries surrounding the Black Sea, Hungary and the Balkans. They were known early on in England as Danubian geese and the Spanish and Italians once referred to the breed as Danubio due to importations from the lower Danube river area. So they probably got their current name from their most recent site of importation at Sebastopol.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/chineseCard.jpeg', 'Chinese Geese', 17, 'The White Chinese goose is smaller than the Embden or Toulouse. It can be noisy but is the most prolific egg-laying goose available. Its most distinguishing feature is the one that sets it apart from the African, its raised knob is more prominent.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/romanCard.jpeg', 'Roman Geese', 28, 'The Roman Tufted breed is not very common but it is especially popular in North America. Its crest is due to a group of feathers standing upright on its head, causing the appearance of a small helmet on its head. This small plump bird tends to be active and alert and more docile than defiant. It also has a friendly personality. Roman Tufted geese weigh 11.5-14 lbs, and the females lay 20-30 large, white eggs per year.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/buffGooseCard.jpeg', 'Buff Geese', 30, 'The American Buff is a rare domestic goose from the U.S. that is a beautiful apricot-fawn color. This very calm-natured goose sports buff-colored feathers on it back, and its sides are edged with creamy white. The Buffs abdomen is nearly white, and its legs may fade to pink during laying, or when green grass is not available.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/embdenCard.jpeg', 'Embden Geese', 22, 'The Embden is the most popular goose for eating. They are a nice strong bird with blue eyes and orange beaks and feet. They have all white plumage, and you will be able to tell the males by the color of their feathers when they are very young. The grey down on the males is much lighter than females when they are very young.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/pilgrimCard.jpeg', 'Pilgrim Geese', 31, 'Pilgrims are the only domestic goose breed in which you can distinguish males from females at any age. As goslings, the males are yellow and light gray with lighter colored bills whereas the females have a deeper gray-green down and a darker bill. Mature males are white with a touch of gray on their rump or wings and mature females are gray in color like a Toulouse but often with white on their heads. Pilgrim geese are very calm and have a reputation for being excellent parents. The fertility of their eggs is low, however, in our experience, it averages about 60% over the complete season. Pilgrim geese weigh 13-15 lbs, and the females lay 20-25 large, white eggs per year.'),
//(873949768395784194, 874505992323694593, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/dewlapCard.jpeg', 'Dewlap Toulouse Geese', 105, 'In England during the 1850s, the Large Dewlap Toulouse was developed for exhibition purposes from the common Toulouse. This unique breed has a large dewlap of skin hanging below its beak, a deep keel hanging from its breast, and two lobes in its full paunch. Also, this breed will continue to grow for several years, not reaching its peak development until it is at least three years old. Though fertility can sometimes be a problem with this breed, the fertile eggs hatch as well as all the other breeds. For the breeding season, you want to keep your goose trim and fit (as with all goose breeds). However, if you want to show your Large Dewlap Toulouse, you will want to get them as heavy as possible.')

//CHICKENS DONE:
//VALUES (873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/silkieCard.jpeg', 'Silkie Chickens', 5, 'Silkie chickens get their name from their trademark fluffy plumage that feels like silk to the touch. Their soft, beautiful feathers make this breed a popular choice both as a pet and for exhibition. Silkie bantams originated hundreds of years ago in ancient China. Today they are among the most beloved ornamental breeds in the world. They are naturally calm and affectionate. They are therefore perfect for the small backyard flock. Because Silkies are small, friendly, and love cuddling, they are a great breed for children. Silkie hens are broody and attentive mothers. They make a great option for anyone interested in breeding ornamental chickens to hatch under Silkie hens. Compared to larger breeds, Silkies are easy keepers that eat less and require less space.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/brahmaCard.jpeg', 'Brahma Chickens', 6, 'Brahmas thrive best on dry, well-drained soils and in moist, cool climates. The feathering of their shanks and toes is a problem where the ground is damp and muddy as the mud clings to the feathers and keeping their feet wet and causing their toes to be prone to frostbite. It was popularly known as the least susceptible chicken to cold and exposure, owing this strength to its pea comb and tight feathering with down through all sections. It is not an ideal fowl for southern climates, where they need ample shade and water as they do not tolerate the heat well. The breed is easy to contain, as its size and weight making it unable to fly over low fences very easily. They also stand confinement extremely well, but also like to spend a majority of their day foraging, although Brahmas are not wide ranging fowl or as active in scratching as the Mediterranean breeds. They have calm and docile personalities, and are not flighty or skittish. They are not aggressive with other breeds and because of their size are not usually intimidated. Although they are friendly with people, their size can intimidate smaller children. Due to their size, they can require a lot of feed. '),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/rhodeRedsCard.jpeg', 'Rhode Island Red Chickens', 3, 'Rhode Island may be Americas smallest state, but the breed developed there in the late 1800s made huge changes in chicken husbandry. The Rhode Island Reds amazing ability to lay about 265 eggs a year made it famous worldwide and became the parent of several modern hybrid egg layers. These glossy mahogany-colored hens with black tail feathers are as beautiful as they are gentle and productive.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/plymouthCard.jpeg', 'Plymouth Rock Chickens', 4, ' They are meant for a small farm that has a backyard coop. These birds lay eggs year-round. Not only that, but their plumpness is great for a roasted chicken. Barred Plymouth Rocks have a single comb and are heat and cold hardy.  Baby Barred Plymouth Rock Chickens have a docile personality, which makes them nice birds to have around the backyard. The hen and rooster get along with others because they have a gentle disposition. They even get along with other pets. This breed has a good ability to forage'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/ayamCard.jpeg', 'Ayam Cemani Chickens', 45, 'Who is the rarest and most sought-after chicken breed on the planet? Ayam Cemani Chickens of course! They originate in Indonesia and have most everything black; feathers, skin, comb to wattles, flesh, organs, black bones and all…wow! This makes this chicken breed one of the most beautiful chickens on the planet, hailing them as The Lamborghini of Poultry. We like to think of them as a gothic and cool/hip chicken breed that are also beneficial! In Indonesia, they are known for their mystical healing powers due to their black hyper-pigmentation. Ayam Cemani is a melanistic breed, which means an overdevelopment of melanin. Their ink-black feathers shimmer with a metallic sheen of beetle green and purple in the sun. The Ayam Cemani are generally friendly birds but will assert themselves with other flock members. Hens lay about 60 to 80 tan to cream-colored eggs their first year, after that it can increase to 60-120. Egg sizes vary with this breed and shades of tan hues.  A typical laying cycle lasts for about 20 to 30 eggs, then the hen will stop laying for three to six months, they are not continuous layers. They are a real eye candy here on the farm, and definitely are higher up in the flock hierarchy. They are an intelligent breed, ours coming up to us begging for attention, treats, or just company. They are typically easy going and some of our hens have been excellent mothers to their or other offspring, going broody sitting on eggs often. We would say they do well in all temperatures, thriving more in hotter climates. If you are in a colder climate, protection of the combs and wattles is strongly recommended and if you choose supplemental heat in the winter. Since our stock is acclimated to the Vermont climate they do well in all temperatures.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/wyandotteCard.jpeg', 'Wyandotte Chickens', 15, 'Silver Laced Wyandottes were one of the first American breeds to be created and even today still remain one of the most visually attractive chickens around. She is a dual purpose breed that will lay around 3-4 light brown eggs each week. Hens are not known to be broody but every now and then one will surprise you they make very diligent sitters and great mothers. Wyandotte Chickens appear a bit reserved as they are very calm and docile flock members. They prefer to be with their own kind and are a bit aloof with other breeds.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/orpingtonCard.jpeg', 'Orpington Chickens', 10, 'The Buff Orpington is a delightful chicken perfect for children or beginners. A favorite among backyard chicken keepers, these large dual-purpose breeds are excellent egg layers while being equally suitable for the table. Quick to mature, hardy, and friendly, they are easy to keep and fun to have around. Orpingtons are gentle, docile birds that are easily tamed and make extraordinary pet chickens. With regular contact that builds trust and familiarity, they become affectionate and enjoy human contact. Some even become lap chickens.They get on well with other flock members and are not known for bullying. Nor are they particularly prone to being bullied themselves due to their large size and solid stature. It is, however, recommended to keep them with other docile breeds.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/maranCard.jpeg', 'Maran Chickens', 13, 'Aside from laying very dark brown eggs, all Marans make great dual-purpose birds. They are productive and they grow to a good table weight. Marans have not always been easy to obtain in the United States, and demand still outpaces supply. Black Copper Marans are particularly difficult to come by, but all of the colors included in this assortment are rare. Aside from their dark eggs, their practicality, and their rarity, there is one more reason many people want to raise Marans: their beauty. Regardless of the color, Marans are gorgeous birds.'),
//(873949768395784194, 874505992323661825, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/jerseyGiantCard.jpeg', 'Jersey Giant Chickens', 7, 'Jersey Giants are docile and just gorgeous, with pretty, big eyes and beautiful proportions. While they are larger than most, they are not obviously out of place roaming around in a mixed flock. This breed was developed in New Jersey as a dual-purpose fowl (valued for both meat and eggs). It is not used on commercial farms because it takes a good seven months for them to grow to full size, whereas commercial strains can reach their desired size as early as 5 weeks of age. The Jersey Giant is good-natured and hens are decent layers of brown eggs. Consider adding one to your flock and helping to keep this heritage breed going strong! The largest of the domestic chickens, Jersey Giants are impressive. At full maturity, they make an excellent roasting bird. Jersey Giants sport a single comb and do well in cold weather. Jersey Giants mature slowly and do not reach full size until they are three years of age! ')

//DUCKS DONE:
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/blueRunnerCard.jpeg', 'Blue Runner Ducks', 10, 'Initially bred in Southeast Asia all Runners have ancestry that dates back to Java over 2000 years ago. They were mistakenly named Indian Runners when first imported to England in the 1850s because they arrived on a ship from India the importing family finally disclosed in 1909 that these runners were in fact from Southeast Asia. These Blue Runners have plumage that is slate blue in color and the back feathers are usually laced in a darker shade of slate blue. They have brown eyes and smokey orange to gray shanks and feet. The males have a greenish blue bill and the females have a bluish gray bill. If you intend to breed Blue Runners you should know that they do not breed true and only 50 percent of their progeny will be blue. Runner ducks are hardy because they typically cover hundreds of miles over the course of their lifetime while foraging for seeds insects slugs and other bugs. However they are light in weight at 3.25 to 4 lbs so it is not likely that they will trample your garden or yard. Their egg production is average now as opposed to a century ago due to extensive breeding with an emphasis on coloration. They will lay 100 to 180 large eggs per year. Runner females will lay either white or light green eggs with some laying dark gray or even blackish eggs at the beginning of the season.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/muscovyCard.jpg', 'Muscovy Ducks', 21, 'The Muscovy duck is a duck native to the Americas, from the Rio Grande Valley of Texas and Mexico south to Argentina and Uruguay. Feral Muscovy ducks are found in New Zealand, Australia, and in Central and Eastern Europe. The male Muscovy Duck is the largest duck in North America, but the female is only half his size. After laying 8 to 15 eggs, she does all of the nest defense and raises the ducklings which have sharp claws and hooked bills to climb out of the nest. Most people keep Muscovy ducks for their eggs and companionship, but traditionally, they have been kept for meat as well. This breed lays about 120 eggs per year, and is said to have the highest meat yield of any duck. For these reasons, Muscovy ducks are very popular dual-purpose ducks for homesteads and small farms.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/buffCard.png', 'Buff Ducks', 9, 'The Buff or Buff Orpington was developed by the William Cook family who lived in the Orpington area of Kent, England in the early 1900s. It was developed as a multipurpose bird, with the ability to lay good quantities of eggs along with having the size and feather color to make a good roasting duck. Some even claim that the buff colored feathers are easier to pluck than the white Pekin feathers. These attractive ducks are often kept solely as farm pets or “pond ornaments” due to their generous nature and graceful beauty.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/magpieCard.jpeg', 'Magpie Ducks', 13, 'Black and White Magpie ducklings are very attractive with their black and white down, that is a blueprint of the adult plumage. They are kept primarily for their beauty and for exhibition, but are also useful as a dual-purpose breed for meat and eggs. Magpie Duck have distinvtive markings that make it unique among ducks and a beautiful addition to any flock. The back, tail, and top of the head are either black or blue, while the remainder of the bird is white with sharp, clear distinctions between the white and colored areas. This Welsh breed was developed in the 1900s by M.C. Gower Williams and Oliver Drake as a beautiful yet productive bird. It is believed to have been created from a mix of Runner, Huttegem, and Termonde ducks. The Magpie first arrived in the United States in the 1960s, and they are regarded as fi ne egg producers. They are active foragers as well.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/khakiCampbellCard.jpeg', 'Khaki Campbell Ducks', 8, 'The Khaki Campbell is one of the more famous and popular duck breeds due to its excellent egg production. It was introduced in 1901 by Mrs. Adele Campbell of Gloucestershire, England. She experimented with Runners crossed with Rouen and Mallards but never revealed the exact genetic makeup of her Campbells. The advantage over the pure Runner was a more useful carcass for meat and improved egg production. Though they have been turned into an exhibition type breed, she was adamant that her birds were designed for production, not the exhibition hall. Initially they were a fairly mixed color breed but later an emphasis was placed on the current khaki color. It is interesting that at the same time the khaki color was being bred into the Campbell, there was a patriotic fervor for the British troops fighting the Boer War who also wore the khaki color. Once the "Khaki" was attached to "Campbell", the breed gained even more popularity. The Khaki Campbell gained even more renown due to the egg laying contests where it averaged up to 39 more eggs laid than the second best breed. One Khaki Campbell laid 346 eggs in 365 days while another laid one egg a day for 225 straight days!')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/callCard.jpeg', 'Call Ducks', 30, 'Call Ducks are very tame and great with children. They are extremely active and animated and are a lot of fun to watch. The females are very loud though, so be aware that neighbors may find them annoying and that you may not want to place your Call Duck enclosure close to your bedroom window. Their chattiness is very cute, and they will even interact with humans. If alarmed, Call Ducks can fly and are exceptional fliers. Call Ducks were developed in the mid-1800s in Great Britain supposedly from old Dutch lines of Coy or Decoy Ducks. The small size was bred into them so they could lure larger wild ducks into funnel traps and then be able to fit through the trap exit hole and escape the trap, leaving the larger ducks inside. They were bred for their calling. Their call is very high pitched, carries well over long distances, luring wild ducks to get within range of hunters. The original Call Duck lines were made up of hard-working birds with strong working abilities. In the 1900s the rules and popularity of hunting were in a state of change, and Call Ducks were becoming rarer and rarer. However, around the middle of the 20th century, interest in Call Ducks was revived, and today they are one of the most popular breeds of duck for exhibition and show.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/whiteCrestedCard.jpg', 'White Crested Ducks', 10, 'Crested ducks are a domestic breed with fairly unknown origins, even though their existence dates back more than 2,000 years. These regal looking poultry birds were traditionally kept for meat and eggs but are now largely kept as pets. The cresting on these ducks is also sometimes found in mallards, which nearly all duck breeds originated from, as a mutation. Through selective breeding for the trait, the crested duck breed was ultimately developed and standards set. The crest is a heterozygous for a mutation that is genetic and causes a skull deformity. The dominant gene mutation causes a gap to grow in the duck embryo’s skull. In this gap a mass of fatty tissue emerges. On the fatty tissue feathers start to grow, creating either large and full or rather skinny crests that are less broad.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/pekinCard.jpg', 'Pekin Ducks', 12, 'The Pekin duck is among the most popular breeds kept in the United States, both in backyards and on homesteads across the country. Pekin ducks are a multi-purpose breed, meaning they have traditionally been raised for egg and meat production. As noted, Pekin ducks, both hens, and drakes are known to be friendly and non-aggressive poultry birds. They sometimes accept being petted by those who are raising them as either a pet or egg bird. Handling the ducklings frequently from the time they are hatched will help get the birds accustomed to being held and touched if this is an important consideration for you.')
//VALUES (873949768395784194, 874505992323563521, 'https://jaclynsimages.s3.us-east-2.amazonaws.com/cayugaCard.jpg', 'Cayuga Ducks', 8, 'The Cayuga duck is used for meat and egg production and does well at poultry shows. The name comes from where it was once very popular, Cayuga Lake, New York State. Admitted into the American Standard of Perfection in 1874. Noted feature is the iridescent beetle green color coming from the black feathers in the correct light. However, as Cayugas age, they naturally molt into gradually more white feathering — more so in hens than in drakes. The Cayuga duck is one of the most popular ducks for showing. They are very active foragers and love to eat snails, slugs and other destructive insects. The Cayuga duck is calm and does not fly and lays both white and darker eggs. The darker eggs have a dark film on the egg shell and are really not a dark shell.')

const insertTypes = `INSERT INTO types(animal_id, type_name, type_image)
VALUES (873949768395784194, 'ducks', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/ducklings.jpg'),
(873949768395784194, 'chickens', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/chickenCard.jpg'),
(873949768395784194, 'geese', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/geese.jpg'),
(873949768395849730, 'lizards', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/lizards.jpg'),
(873949768395849730, 'frogs', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/frogs.jpg'),
(873949768395849730, 'turtles', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/turtles.jpg'),
(873949768395882498, 'black soldier flies', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/fly.jpg'),
(873949768395882498, 'mealworms', 'https://jaclynsimages.s3.us-east-2.amazonaws.com/mealworm.jpeg')
`

const createUserTable = `CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zipcode INT,
    phone INT
)`

const createCartTable = `CREATE TABLE cart (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  breed_id INT NOT NULL REFERENCES breeds(breed_id),
  quantity INT
)`


const insertAnimals = `INSERT INTO animals (type)
VALUES('fowl'),('lizards'),('bugs')
`
const alterAnimalsTable = `ALTER TABLE animals ADD image VARCHAR(1000)
`
const alterTypesTable = `ALTER TABLE breeds RENAME TO types`
const alterTypesColumn = `ALTER TABLE types RENAME COLUMN breed_image TO type_image`
const addImagesToTypes = `UPDATE animals SET image = $1 WHERE id = $2`
const updateDuckType = `UPDATE types SET type_image = 'https://jaclynsimages.s3.us-east-2.amazonaws.com/ducklings.jpg' WHERE type_name = 'ducks'`

module.exports = {
  createAnimalTable,
  createTypesTable,
  createBreedsTable,
  createUserTable,
  createCartTable,
  createReviewTable,
  insertAnimals,
  insertTypes,
  insertBreeds,
  alterAnimalsTable,
  alterTypesTable,
  alterTypesColumn,
  addImagesToTypes, 
  updateDuckType
}
